// .github/labeler.yml

enable:
  issues: true
  prs: true

comments:
  issues: |
    라벨 지정 제대로 되었는지 체크 한 번씩 하기 🧞‍♂️ 작업도 화이팅 !!!!!!! 😍
  prs: |
    라벨 지정 제대로 되었는지 체크 한 번씩 하기 🧞‍♂️ 고생했어요 다음 작업도 화이팅 !!!!!! 😍
    
labels:
  ':tada: init':
    include:
      - '\binit\b'
  ':sparkles: feat':
    include:
      - '\bfeat\b'
  ':bug: fix':
    include:
      - '\bfix\b'
  ':package: chore':
    include:
      - '\bchore\b'
  ':recycle: refactor':
    include:
      - '\brefactor\b'
  ':lipstick: design':
    include:
      - '\bdesign\b'
  ':ambulance: hotfix':
    include:
      - '\bhotfix\b'
  ':memo: docs':
    include:
      - '\bdocs\b'
